
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SumaServicioImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8080/SumaServicioImplService/SumaServicioImpl?wsdl")
public class SumaServicioImplService
    extends Service
{

    private final static URL SUMASERVICIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUMASERVICIOIMPLSERVICE_EXCEPTION;
    private final static QName SUMASERVICIOIMPLSERVICE_QNAME = new QName("http://beans/", "SumaServicioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SumaServicioImplService/SumaServicioImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUMASERVICIOIMPLSERVICE_WSDL_LOCATION = url;
        SUMASERVICIOIMPLSERVICE_EXCEPTION = e;
    }

    public SumaServicioImplService() {
        super(__getWsdlLocation(), SUMASERVICIOIMPLSERVICE_QNAME);
    }

    public SumaServicioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUMASERVICIOIMPLSERVICE_QNAME, features);
    }

    public SumaServicioImplService(URL wsdlLocation) {
        super(wsdlLocation, SUMASERVICIOIMPLSERVICE_QNAME);
    }

    public SumaServicioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUMASERVICIOIMPLSERVICE_QNAME, features);
    }

    public SumaServicioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumaServicioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSumarWs
     */
    @WebEndpoint(name = "SumaServicioImplPort")
    public ServicioSumarWs getSumaServicioImplPort() {
        return super.getPort(new QName("http://beans/", "SumaServicioImplPort"), ServicioSumarWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarWs
     */
    @WebEndpoint(name = "SumaServicioImplPort")
    public ServicioSumarWs getSumaServicioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "SumaServicioImplPort"), ServicioSumarWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUMASERVICIOIMPLSERVICE_EXCEPTION!= null) {
            throw SUMASERVICIOIMPLSERVICE_EXCEPTION;
        }
        return SUMASERVICIOIMPLSERVICE_WSDL_LOCATION;
    }

}
